variable:
   profiles : dev

spring:
  datasource:
    # mysql 配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nkuvr_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: toor

    # 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    initiaSize: 1
    minIdle: 1
    maxActive: 3
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #验证库是否正常sql
    validationQuery: select 'x'
    #空闲时验证，防止连接断开
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  # thymeleaf 模板配置
  thymeleaf:
    cache: false
    mode: HTML

# 端口配置
server:
  port: 8082


# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 分页插件配置
pagehelper:
  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  reasonable: true
  #是否支持接口参数来传递分页参数，默认false
  supportMethodsArguments: true
  params: count=countSql
  helper-dialect: mysql

