spring:
  datasource:
    # mysql 配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nkuvr_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: toor
    # 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource

# 端口配置
server:
  port: 8082

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml